version: '3'

services:
  servicewithmongo:
    image: servicewithmongo
    build:
      context: .
      dockerfile: ServiceWithMongo/Dockerfile
    depends_on: 
      - nosql.data

  nosql.data:
    image: mongo
    ports:
      - "27017:27017"
